### PR TITLE
Run OpenELIS migrations during update-config

### PR DESCRIPTION
**Pull request by R-VdP**
When running the update-config command, migrations are performed for OpenMRS but not for OpenELIS. This commit takes the logic to run the elis migrations out of the bahmni-lab role which is only executed during installation and puts it in a separate role which we can also run during update-config.

Ideally we would generalise this further to any other migrations in bahmni.

### CODE REVIEW

**Comment by sumanmaity112** [comment]
Hi @RdN-MSF,
is there any JIRA card for this issue? If `yes`, please update the commit message with JIRA card number. If `no`, please create a JIRA card and update the commit message

**Comment by RdN-MSF** [comment]
Hi @sumanmaity112 
I don't have access to jira, could you either give me access or create the ticket for me then?

**Comment by sumanmaity112** [comment]
@angshu @binduak Can you please give JIRA access to @RdN-MSF

**Comment by binduak** [comment]
@sumanmaity112 I don't have JIRA admin access. @angshu can you help with the access to @RdN-MSF

**Comment by angshu** [comment]
@RdN-MSF you can create an atlassian id  and self join in Bahmni JIRA. You should be create a card in JIRA. Once you are done, ping on Slack or talk with the card number, so someone from product can slot it in the right release.

**Pull request closed without merging**
